import { homeScreenTypes } from '../types/homeScreenTypes';

export const response: homeScreenTypes[] = [
  {
    imgUri: 'https://picsum.photos/id/237/200/100',
    id: 'id1',
    mainTtle: '이거 글자 길어지면 이런식으로 점점점점점점ㅈ',
    address: '여기도 원래는 주소 나오는 곳인데 이런식으로 점점점점점점',
    distance: '도보 10분',
    roomType: '원룸',
    area: '7평',
    pinned: true,
  },
  {
    imgUri: 'https://picsum.photos/id/23/200/100',
    id: 'id2',
    mainTtle: '카페거리 맞은편 풀옵션',
    address: '경기도 화성시 동탄환대로 27길 45',
    distance: '도보 10분',
    roomType: '원룸',
    area: '7평',
    pinned: false,
  },
  {
    imgUri: 'https://picsum.photos/id/434/200/100',
    id: 'id31',
    mainTtle: '카페거리 맞은편 풀옵션',
    address: '경기도 화성시 동탄환대로 27길 45',
    distance: '도보 10분',
    roomType: '원룸',
    area: '7평',
    pinned: true,
  },
  {
    imgUri: 'https://picsum.photos/id/14/200/100',
    id: 'id4',
    mainTtle: '카페거리 맞은편 풀옵션',
    address: '경기도 화성시 동탄환대로 27길 45',
    distance: '도보 10분',
    roomType: '원룸',
    area: '7평',
    pinned: false,
  },
  {
    imgUri: 'https://picsum.photos/id/14/200/100',
    id: 'id5',
    mainTtle: '카페거리 맞은편 풀옵션',
    address: '경기도 화성시 동탄환대로 27길 45',
    distance: '도보 10분',
    roomType: '원룸',
    area: '7평',
    pinned: true,
  },
  {
    imgUri: 'https://picsum.photos/id/114/200/100',
    id: 'id6',
    mainTtle: '카페거리 맞은편 풀옵션',
    address: '경기도 화성시 동탄환대로 27길 45',
    distance: '도보 10분',
    roomType: '원룸',
    area: '7평',
    pinned: true,
  },
  {
    imgUri: 'https://picsum.photos/id/114/200/100',
    id: 'id7',
    mainTtle: '카페거리 맞은편 풀옵션',
    address: '경기도 화성시 동탄환대로 27길 45',
    distance: '도보 10분',
    roomType: '원룸',
    area: '7평',
    pinned: false,
  },
  {
    imgUri: 'https://picsum.photos/id/114/200/100',
    id: 'id1238',
    mainTtle: '카페거리 맞은편 풀옵션',
    address: '경기도 화성시 동탄환대로 27길 45',
    distance: '도보 10분',
    roomType: '원룸',
    area: '7평',
    pinned: false,
  },
];
